Repository ros2/ros1_bridge, pull requests merged in 2018-06, with the labels that each got.

#117 migrate launch -> launch.legacy
  test/test_dynamic_bridge.py.in
Labels: in review

#119 use catkin_pkg to parse packages
  package.xml
  ros1_bridge/__init__.py
Labels: in review

#121 include module name which wasn't found in error message
  cmake/find_ros1_package.cmake
Labels: enhancement, in review

#122 update README to use colcon and ROS Melodic
  README.md
Labels: in review

#123 print message for all ROS 2 message pkgs
  CMakeLists.txt
Labels: enhancement, in review

#124 print service pairs as well
  include/ros1_bridge/bridge.hpp
  resource/get_mappings.cpp.em
  ros1_bridge/__init__.py
  src/dynamic_bridge.cpp
Labels: enhancement, in review

#126 Prepare 0.5.0
  package.xml
Labels: in progress
