Repository ros2/ros1_bridge, pull requests merged in 2019-05, with the labels that each got.

#188 Corrected publish calls with shared_ptr signature
  src/simple_bridge.cpp
Labels: in review

#190 Corrected publish calls with shared_ptr signature, leftovers
  include/ros1_bridge/factory.hpp
  src/simple_bridge_1_to_2.cpp
Labels: in review

#189 changes to avoid deprecated API's
  include/ros1_bridge/factory.hpp
  src/simple_bridge.cpp
  src/simple_bridge_1_to_2.cpp
  src/simple_bridge_2_to_1.cpp
Labels: in progress

#192 fix build by passing options
  include/ros1_bridge/factory.hpp
  src/simple_bridge.cpp
Labels: bug, in review

#191 Adds interface type to ROS2 message type name
  resource/interface_factories.cpp.em
Labels: bug, in review

#194 Use interface kind names properly in ROS2 interface type names.
  resource/get_mappings.cpp.em
  resource/interface_factories.cpp.em
Labels: bug, in review

#174 Support field selection
  doc/index.rst
  resource/interface_factories.cpp.em
  ros1_bridge/__init__.py
Labels: enhancement, in progress

#193 Handle launch_testing assertExitCodes correctly
  test/test_services_across_dynamic_bridge.py.in
Labels: in review

#197 Disable rosout logging for the bridge
  CMakeLists.txt
  src/dynamic_bridge.cpp
Labels: bug, in review

#198 add missing test dependency in Crystal
  package.xml
Labels: bug, in review

#201 Add documentation of workspace setup for custom messages
  README.md
  doc/index.rst
Labels: enhancement
