Repository ros2/ros1_bridge, pull requests merged in 2019-08, with the labels that each got.

#209 fix typename in static bridge
  src/static_bridge.cpp
Labels: bug, in review

#176 add services bridging to parameter_bridge
  src/parameter_bridge.cpp
Labels: enhancement, in review

#211 Clearer instructions for example ros1->ros2
  README.md
Labels: enhancement
