Repository ros2/ros1_bridge, pull requests merged in 2019-03, with the labels that each got.

#170 invalidate wrong cached result for diagnostic_msgs
  CMakeLists.txt
Labels: enhancement, in review

#167 Switch to rclcpp logging and improve messages
  include/ros1_bridge/factory.hpp
  include/ros1_bridge/factory_interface.hpp
  src/bridge.cpp
Labels: in review

#171 Add launch along with launch_testing as test dependencies.
  package.xml
Labels: in review

#172 [backport] export find_ros1_package cmake extras
  CMakeLists.txt
  cmake/find_ros1_package.cmake
  package.xml
Labels: in progress

#178 Allows propagations of cmd args to rclcpp::init
  src/dynamic_bridge.cpp
Labels: in progress, in review

#180 use yaml.safe_load instead of deprecated yaml.load
  ros1_bridge/__init__.py
Labels: in review
