Repository ros2/ros1_bridge, pull requests merged in 2020-12, with the labels that each got.

#298 fix bug with sizeof when type of the arrays differ
  resource/interface_factories.cpp.em
Labels: bug

#300 fix bug with sizeof when type of the arrays differ (#298)
  resource/interface_factories.cpp.em
Labels: bug

#301 [backport foxy] support idl files on the ROS 2 side of the bridge
  CMakeLists.txt
  resource/interface_factories.cpp.em
  ros1_bridge/__init__.py
Labels: bug, enhancement

#302 [backport eloquent] support idl files on the ROS 2 side of the bridge
  CMakeLists.txt
  resource/interface_factories.cpp.em
  ros1_bridge/__init__.py
Labels: bug, enhancement

#297 very minor typo in comments
  src/parameter_bridge.cpp
Labels: more-information-needed
